export enum AUTH_ACTIONS_TYPE {
    SET_USER = 'SET_USER',
    SET_IS_INITIALIZED = 'SET_IS_INITIALIZED',
    SET_LOADING = 'SET_LOADING',
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    LOGOUT = 'LOGOUT'
}